# Generated by Django 4.1 on 2022-10-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(upload_to='pic1/')),
                ('pic2', models.ImageField(upload_to='pic2/')),
                ('pic3', models.ImageField(upload_to='pic3/')),
                ('pic4', models.ImageField(upload_to='pic4/')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
