# Generated by Django 4.1 on 2022-10-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='price_set',
            field=models.CharField(default='$1000 To $5000', max_length=100),
        ),
    ]
